### ISSUE TITLE
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlencode'

### ISSUE THREAD

**Issue by kneekill** [tylertreat/BigQuery-Python#102]
Hello! 

Here is my error code:
`Traceback (most recent call last):
  File "/Users/Nikhil/Dropbox/Eclipse Workspace/BigQueryAPI/main/BigQueryWrapperTes.py", line 19, in <module>
    private_key_file=key, readonly=True)
  File "/Library/Python/2.7/site-packages/bigquery/client.py", line 146, in get_client
    service_url=service_url)
  File "/Library/Python/2.7/site-packages/bigquery/client.py", line 158, in _get_bq_service
    discoveryServiceUrl=service_url)
  File "/Library/Python/2.7/site-packages/oauth2client/util.py", line 135, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/googleapiclient/discovery.py", line 207, in build
    cache)
  File "/Library/Python/2.7/site-packages/googleapiclient/discovery.py", line 254, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 616, in new_request
    self._refresh(request_orig)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 873, in _refresh
    self._do_refresh_request(http_request)
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 900, in _do_refresh_request
    body = self._generate_refresh_request_body()
  File "/Library/Python/2.7/site-packages/oauth2client/client.py", line 1613, in _generate_refresh_request_body
    body = urllib.parse.urlencode({
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'urlencode'`

I initially attempted to use just my JSON key to authenticate but it was throwing me an error asking for the PEM key then this error gets thrown when I provided my p12 key. 

Any ideas?

**Comment by dylancaponi-noo** [comment]
How did you solve this issue?

**Comment by kneekill** [comment]
I encountered this issue on macOS so if that is the case for you as well, you can refer to this thread: https://github.com/google/google-api-python-client/issues/100
