### ISSUE TITLE
AssertionError: No api proxy found for service "memcache"

### ISSUE THREAD

**Issue by ricardorlopes** [tylertreat/BigQuery-Python#106]
When I run this code manually everything works fine.. but when I run it inside my code, it prints a warning message which is bothering me and I don't know why it happens..
```
        client = get_client(project,
                                 service_account=self.service_account,
                                 private_key_file=self.google_key,
                                 readonly=False)
```

> WARNING:root:No api proxy found for service "memcache"
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/appengine_memcache.py", line 42, in get
>     return memcache.get(url, namespace=NAMESPACE)
>   File "/home/ricci/google_appengine/google/appengine/api/memcache/__init__.py", line 559, in get
>     rpc = self.get_multi_async([key], namespace=namespace, for_cas=for_cas)
>   File "/home/ricci/google_appengine/google/appengine/api/memcache/__init__.py", line 612, in get_multi_async
>     self.__get_hook, user_key)
>   File "/home/ricci/google_appengine/google/appengine/api/memcache/__init__.py", line 381, in _make_async_call
>     rpc = create_rpc()
>   File "/home/ricci/google_appengine/google/appengine/api/memcache/__init__.py", line 295, in create_rpc
>     return apiproxy_stub_map.UserRPC('memcache', deadline, callback)
>   File "/home/ricci/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 414, in __init__
>     self.__rpc = CreateRPC(service, stubmap)
>   File "/home/ricci/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 68, in CreateRPC
>     assert stub, 'No api proxy found for service "%s"' % service
> AssertionError: No api proxy found for service "memcache"
> WARNING:root:No api proxy found for service "memcache"
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/appengine_memcache.py", line 48, in set
>     memcache.set(url, content, time=int(self._max_age), namespace=NAMESPACE)
>   File "/home/ricci/google_appengine/google/appengine/api/memcache/__init__.py", line 764, in set
>     namespace=namespace)
>   File "/home/ricci/google_appengine/google/appengine/api/memcache/__init__.py", line 869, in _set_with_policy
>     time, '', namespace)
>   File "/home/ricci/google_appengine/google/appengine/api/memcache/__init__.py", line 971, in _set_multi_async_with_policy
>     (server_keys, user_key))
>   File "/home/ricci/google_appengine/google/appengine/api/memcache/__init__.py", line 381, in _make_async_call
>     rpc = create_rpc()
>   File "/home/ricci/google_appengine/google/appengine/api/memcache/__init__.py", line 295, in create_rpc
>     return apiproxy_stub_map.UserRPC('memcache', deadline, callback)
>   File "/home/ricci/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 414, in __init__
>     self.__rpc = CreateRPC(service, stubmap)
>   File "/home/ricci/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 68, in CreateRPC
>     assert stub, 'No api proxy found for service "%s"' % service
> AssertionError: No api proxy found for service "memcache"

Can someone help me with this?

Thanks

**Comment by ricardorlopes** [comment]
It's a conflict between libraries.
